# Generated by Django 4.2.7 on 2023-12-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_id_usuario_alter_pais_nombre_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
