# Generated by Django 4.2.7 on 2023-12-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_pais_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='numero',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
