# Generated by Django 4.2.7 on 2023-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_noticia_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='id',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='numero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
