# Generated by Django 4.2.7 on 2023-12-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_noticia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='usuario@gmail.com', max_length=50),
            preserve_default=False,
        ),
    ]
